spring:
  datasource:
        # 驱动配置信息
        url: jdbc:oracle:thin:@192.168.81.42:1521/NINVOICE
        username: jrwz2_zx
        password: jrwz2_zx
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: oracle.jdbc.driver.OracleDriver

        # 连接池的配置信息
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
env:
  currect: dev
bllose:
  test:
    name: bllose
quartz:
  job1:
    name: test
    gourp: testG
    function: sayHello
    trigger:
      name: test
      time: 0 31 10 * * ?
#logging:
#  level:
#    root: trace
#  path: /E:/logs/webDemo
#  file: webDemo.log
#  pattern:
#    file: file %d{yyyy-MMM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{15} - %msg%n
#    console: concole %d{yyyy-MMM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{15} - %msg%n
